/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class G_co extends javax.swing.JFrame {

    /**
     * Creates new form Connexion
     */
    public G_co() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        gtitre = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        nombdd = new javax.swing.JLabel();
        mdp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        casebdd = new javax.swing.JTextField();
        casemdp = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        auteur = new javax.swing.JLabel();
        auteur1 = new javax.swing.JLabel();
        auteur2 = new javax.swing.JLabel();
        auteur3 = new javax.swing.JLabel();
        fondimage = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel1.setLayout(null);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Projet Java 2019");
        jPanel1.add(gtitre);
        gtitre.setBounds(139, 11, 456, 86);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(255, 255, 255));
        ptitre.setText("Connectez-vous :");
        jPanel1.add(ptitre);
        ptitre.setBounds(239, 108, 206, 35);

        nombdd.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        nombdd.setForeground(new java.awt.Color(255, 255, 255));
        nombdd.setText("Nom de la Bdd :");
        jPanel1.add(nombdd);
        nombdd.setBounds(204, 182, 151, 33);

        mdp.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        mdp.setForeground(new java.awt.Color(255, 255, 255));
        mdp.setText("Mot de pass :");
        jPanel1.add(mdp);
        mdp.setBounds(234, 221, 121, 33);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(160, 340, 410, 10);

        casebdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                casebddActionPerformed(evt);
            }
        });
        jPanel1.add(casebdd);
        casebdd.setBounds(373, 191, 110, 20);
        jPanel1.add(casemdp);
        casemdp.setBounds(373, 230, 110, 20);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButton1.setText("Connexion");
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 280, 160, 41);

        auteur.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        auteur.setForeground(new java.awt.Color(255, 255, 255));
        auteur.setText("Auteurs :");
        jPanel1.add(auteur);
        auteur.setBounds(330, 350, 58, 30);

        auteur1.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        auteur1.setForeground(new java.awt.Color(255, 255, 255));
        auteur1.setText("Mathilde GIRAUDON");
        jPanel1.add(auteur1);
        auteur1.setBounds(290, 400, 135, 23);

        auteur2.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        auteur2.setForeground(new java.awt.Color(255, 255, 255));
        auteur2.setText("Junayet BHUIYAN");
        jPanel1.add(auteur2);
        auteur2.setBounds(300, 380, 127, 23);

        auteur3.setFont(new java.awt.Font("Segoe Print", 2, 12)); // NOI18N
        auteur3.setForeground(new java.awt.Color(255, 255, 255));
        auteur3.setText("Victor TROUSSARD");
        jPanel1.add(auteur3);
        auteur3.setBounds(290, 420, 146, 20);

        fondimage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/FondEspace.jpg"))); // NOI18N
        fondimage.setText("jLabel10");
        jPanel1.add(fondimage);
        fondimage.setBounds(0, 0, 700, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void casebddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_casebddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_casebddActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel auteur;
    private javax.swing.JLabel auteur1;
    private javax.swing.JLabel auteur2;
    private javax.swing.JLabel auteur3;
    private javax.swing.JTextField casebdd;
    private javax.swing.JPasswordField casemdp;
    private javax.swing.JLabel fondimage;
    private javax.swing.JLabel gtitre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mdp;
    private javax.swing.JLabel nombdd;
    private javax.swing.JLabel ptitre;
    // End of variables declaration//GEN-END:variables
}
