/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class SSupprimer extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public SSupprimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoece = new javax.swing.JLabel();
        gtitre = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        classe = new javax.swing.JLabel();
        choixclasse = new javax.swing.JComboBox<>();
        textclasse = new javax.swing.JLabel();
        oui = new javax.swing.JRadioButton();
        non = new javax.swing.JRadioButton();
        idelève = new javax.swing.JLabel();
        caseid = new javax.swing.JTextField();
        buttonok = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        matiere = new javax.swing.JLabel();
        choixmatiere = new javax.swing.JComboBox<>();
        bulletin = new javax.swing.JLabel();
        choixbulletin = new javax.swing.JComboBox<>();
        buttonselionner = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        idevaluation = new javax.swing.JLabel();
        caseidevaluation = new javax.swing.JTextField();
        buttonsupprimer = new javax.swing.JButton();
        buttonretour = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel1.setLayout(null);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        jPanel1.add(logoece);
        logoece.setBounds(10, 11, 267, 67);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Mise à jour évaluation");
        jPanel1.add(gtitre);
        gtitre.setBounds(388, 10, 280, 36);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Enseignant");
        jPanel1.add(ptitre);
        ptitre.setBounds(452, 50, 150, 35);

        titre.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        titre.setForeground(new java.awt.Color(204, 204, 255));
        titre.setText("Supprimer une évaluation :");
        jPanel1.add(titre);
        titre.setBounds(190, 90, 260, 33);

        classe.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        classe.setForeground(new java.awt.Color(255, 255, 255));
        classe.setText("Sélectionner une classe :");
        jPanel1.add(classe);
        classe.setBounds(92, 151, 160, 23);

        choixclasse.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixclasse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        choixclasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixclasseActionPerformed(evt);
            }
        });
        jPanel1.add(choixclasse);
        choixclasse.setBounds(255, 148, 90, 29);

        textclasse.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        textclasse.setForeground(new java.awt.Color(255, 255, 255));
        textclasse.setText("Souhaitez-vous sélectionner tous les élèves de la classe ?");
        jPanel1.add(textclasse);
        textclasse.setBounds(92, 183, 350, 23);

        oui.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        oui.setText("Oui");
        jPanel1.add(oui);
        oui.setBounds(460, 170, 50, 31);

        non.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        non.setText("Non");
        jPanel1.add(non);
        non.setBounds(530, 170, 50, 31);

        idelève.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        idelève.setForeground(new java.awt.Color(255, 255, 255));
        idelève.setText("Rentrer l'identifant d'un élève :");
        jPanel1.add(idelève);
        idelève.setBounds(92, 216, 200, 23);
        jPanel1.add(caseid);
        caseid.setBounds(321, 218, 157, 20);

        buttonok.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonok.setText("OK");
        jPanel1.add(buttonok);
        buttonok.setBounds(516, 212, 60, 31);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(92, 261, 478, 13);

        matiere.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        matiere.setForeground(new java.awt.Color(255, 255, 255));
        matiere.setText("Matière :");
        jPanel1.add(matiere);
        matiere.setBounds(90, 280, 60, 23);

        choixmatiere.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixmatiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(choixmatiere);
        choixmatiere.setBounds(180, 280, 120, 29);

        bulletin.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setText("Bulletin :");
        jPanel1.add(bulletin);
        bulletin.setBounds(90, 320, 60, 23);

        choixbulletin.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixbulletin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(choixbulletin);
        choixbulletin.setBounds(180, 320, 120, 29);

        buttonselionner.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonselionner.setText("Selectionner ");
        jPanel1.add(buttonselionner);
        buttonselionner.setBounds(380, 290, 140, 31);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(88, 354, 490, 10);

        idevaluation.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        idevaluation.setForeground(new java.awt.Color(255, 255, 255));
        idevaluation.setText("Evaluation N° :");
        jPanel1.add(idevaluation);
        idevaluation.setBounds(110, 370, 100, 23);
        jPanel1.add(caseidevaluation);
        caseidevaluation.setBounds(230, 370, 180, 20);

        buttonsupprimer.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonsupprimer.setText("Supprimer");
        jPanel1.add(buttonsupprimer);
        buttonsupprimer.setBounds(450, 370, 130, 31);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(300, 420, 90, 31);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setText("jLabel5");
        jPanel1.add(fond);
        fond.setBounds(0, 0, 700, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixclasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixclasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixclasseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SSupprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SSupprimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bulletin;
    private javax.swing.JButton buttonok;
    private javax.swing.JButton buttonretour;
    private javax.swing.JButton buttonselionner;
    private javax.swing.JButton buttonsupprimer;
    private javax.swing.JTextField caseid;
    private javax.swing.JTextField caseidevaluation;
    private javax.swing.JComboBox<String> choixbulletin;
    private javax.swing.JComboBox<String> choixclasse;
    private javax.swing.JComboBox<String> choixmatiere;
    private javax.swing.JLabel classe;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JLabel idelève;
    private javax.swing.JLabel idevaluation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel matiere;
    private javax.swing.JRadioButton non;
    private javax.swing.JRadioButton oui;
    private javax.swing.JLabel ptitre;
    private javax.swing.JLabel textclasse;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
