/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;

/**
 *
 * @author mathi
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page = new javax.swing.JPanel();
        quitter = new javax.swing.JButton();
        gtitre = new javax.swing.JLabel();
        titremenu = new javax.swing.JLabel();
        recherche = new javax.swing.JButton();
        miseaj = new javax.swing.JButton();
        reporting = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        page.setMinimumSize(new java.awt.Dimension(700, 500));
        page.setPreferredSize(new java.awt.Dimension(700, 500));
        page.setLayout(null);

        quitter.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        quitter.setText("Quitter");
        page.add(quitter);
        quitter.setBounds(550, 430, 90, 31);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Bienvenue sur le site de Gestion de l'ECE !");
        page.add(gtitre);
        gtitre.setBounds(90, 120, 520, 30);

        titremenu.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        titremenu.setForeground(new java.awt.Color(204, 204, 255));
        titremenu.setText("Menu :");
        page.add(titremenu);
        titremenu.setBounds(300, 160, 100, 40);

        recherche.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        recherche.setText("Recherche");
        page.add(recherche);
        recherche.setBounds(290, 220, 110, 40);

        miseaj.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        miseaj.setText("Mise à jour");
        miseaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miseajActionPerformed(evt);
            }
        });
        page.add(miseaj);
        miseaj.setBounds(290, 280, 110, 40);

        reporting.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        reporting.setText("Reporting");
        reporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportingActionPerformed(evt);
            }
        });
        page.add(reporting);
        reporting.setBounds(290, 340, 110, 40);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        logo.setText("jLabel4");
        logo.setMaximumSize(new java.awt.Dimension(500, 100));
        logo.setOpaque(true);
        logo.setPreferredSize(new java.awt.Dimension(500, 100));
        page.add(logo);
        logo.setBounds(40, 30, 270, 70);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setLabelFor(gtitre);
        fond.setText("jLabel3");
        fond.setOpaque(true);
        page.add(fond);
        fond.setBounds(0, 0, 700, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miseajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miseajActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_miseajActionPerformed

    private void reportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reportingActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JLabel logo;
    private javax.swing.JButton miseaj;
    private javax.swing.JPanel page;
    private javax.swing.JButton quitter;
    private javax.swing.JButton recherche;
    private javax.swing.JButton reporting;
    private javax.swing.JLabel titremenu;
    // End of variables declaration//GEN-END:variables
}
