/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;

/**
 *
 * @author mathi
 */
public class tableeleve extends javax.swing.JFrame {

    /**
     * Creates new form tableeleve
     */
    public tableeleve() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gtitre = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        logoece = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        casenom = new javax.swing.JLabel();
        caseprenom = new javax.swing.JLabel();
        annees = new javax.swing.JLabel();
        choixannee = new javax.swing.JComboBox<>();
        tableau = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonretour = new javax.swing.JButton();
        matieres = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        textcosult = new javax.swing.JLabel();
        choixmatieres = new javax.swing.JComboBox<>();
        buttonconsulter = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setLayout(null);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Recherche et Informations :");
        jPanel1.add(gtitre);
        gtitre.setBounds(310, 20, 350, 30);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("ELèves");
        jPanel1.add(ptitre);
        ptitre.setBounds(410, 50, 100, 40);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        jPanel1.add(logoece);
        logoece.setBounds(20, 20, 267, 67);

        nom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("Nom : ");
        jPanel1.add(nom);
        nom.setBounds(50, 120, 43, 23);

        prenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.setText("Prénom :");
        jPanel1.add(prenom);
        prenom.setBounds(30, 140, 70, 23);

        casenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        casenom.setForeground(new java.awt.Color(255, 255, 255));
        casenom.setText("Ici nom");
        jPanel1.add(casenom);
        casenom.setBounds(100, 120, 70, 20);

        caseprenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        caseprenom.setForeground(new java.awt.Color(255, 255, 255));
        caseprenom.setText("Ici prenom");
        jPanel1.add(caseprenom);
        caseprenom.setBounds(100, 140, 65, 23);

        annees.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        annees.setForeground(new java.awt.Color(255, 255, 255));
        annees.setText("Année : ");
        jPanel1.add(annees);
        annees.setBounds(40, 170, 51, 23);

        choixannee.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixannee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(choixannee);
        choixannee.setBounds(100, 170, 90, 20);

        jTable1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jTable1ComponentHidden(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        tableau.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        jPanel1.add(tableau);
        tableau.setBounds(140, 210, 452, 90);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(300, 411, 100, 30);

        matieres.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        matieres.setForeground(new java.awt.Color(255, 255, 255));
        matieres.setText("Matière:");
        jPanel1.add(matieres);
        matieres.setBounds(170, 350, 50, 20);

        titre.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        titre.setForeground(new java.awt.Color(255, 255, 255));
        titre.setText("Bulletin Trimestriel");
        jPanel1.add(titre);
        titre.setBounds(270, 150, 180, 50);

        textcosult.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        textcosult.setForeground(new java.awt.Color(255, 255, 255));
        textcosult.setText("Consulterle bulletin détaillé pour chaque matière : ");
        jPanel1.add(textcosult);
        textcosult.setBounds(170, 310, 370, 26);

        choixmatieres.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixmatieres.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        choixmatieres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixmatieresActionPerformed(evt);
            }
        });
        jPanel1.add(choixmatieres);
        choixmatieres.setBounds(250, 350, 140, 29);

        buttonconsulter.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonconsulter.setText("Consulter");
        jPanel1.add(buttonconsulter);
        buttonconsulter.setBounds(440, 350, 110, 30);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setText("jLabel12");
        jPanel1.add(fond);
        fond.setBounds(0, 0, 700, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jTable1ComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1ComponentHidden

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1PropertyChange

    private void choixmatieresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixmatieresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixmatieresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tableeleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tableeleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tableeleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tableeleve.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tableeleve().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel annees;
    private javax.swing.JButton buttonconsulter;
    private javax.swing.JButton buttonretour;
    private javax.swing.JLabel casenom;
    private javax.swing.JLabel caseprenom;
    private javax.swing.JComboBox<String> choixannee;
    private javax.swing.JComboBox<String> choixmatieres;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel matieres;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel ptitre;
    private javax.swing.JScrollPane tableau;
    private javax.swing.JLabel textcosult;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
