/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class G_maj_admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public G_maj_admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gtitre = new javax.swing.JLabel();
        logoece = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        buttoneleve = new javax.swing.JButton();
        buttonprof = new javax.swing.JButton();
        buttonretour = new javax.swing.JButton();
        buttonautre = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Compte Adminnistateur");
        jPanel1.add(gtitre);
        gtitre.setBounds(350, 30, 320, 50);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        logoece.setText("jLabel2");
        jPanel1.add(logoece);
        logoece.setBounds(30, 20, 270, 60);

        titre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(204, 204, 255));
        titre.setText("Que souhaitez-vous mettre à jour :");
        jPanel1.add(titre);
        titre.setBounds(110, 130, 450, 44);

        buttoneleve.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        buttoneleve.setText("Eleves");
        jPanel1.add(buttoneleve);
        buttoneleve.setBounds(290, 200, 100, 30);

        buttonprof.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        buttonprof.setText("Professeurs");
        jPanel1.add(buttonprof);
        buttonprof.setBounds(290, 250, 100, 30);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(300, 390, 80, 30);

        buttonautre.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonautre.setText("Autre");
        buttonautre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonautreActionPerformed(evt);
            }
        });
        jPanel1.add(buttonautre);
        buttonautre.setBounds(290, 300, 100, 30);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setText("jLabel1");
        jPanel1.add(fond);
        fond.setBounds(-10, 0, 700, 510);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonautreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonautreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonautreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G_maj_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G_maj_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G_maj_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G_maj_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G_maj_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonautre;
    private javax.swing.JButton buttoneleve;
    private javax.swing.JButton buttonprof;
    private javax.swing.JButton buttonretour;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
