/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;

/**
 *
 * @author mathi
 */
public class GinfoProf extends javax.swing.JFrame {

    /**
     * Creates new form GinfoProf
     */
    public GinfoProf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoece = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        gtitre = new javax.swing.JLabel();
        buttonvalider = new javax.swing.JButton();
        caseid = new javax.swing.JTextField();
        buttonquitter = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jPanel1.setLayout(null);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        logoece.setText("jLabel1");
        jPanel1.add(logoece);
        logoece.setBounds(19, 11, 266, 67);

        ptitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Indentifiez-vous :");
        jPanel1.add(ptitre);
        ptitre.setBounds(230, 150, 210, 44);

        id.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("Rentrer un identifiant :");
        jPanel1.add(id);
        id.setBounds(90, 250, 143, 23);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Recherche d'un Proffeseur");
        jPanel1.add(gtitre);
        gtitre.setBounds(330, 30, 330, 50);

        buttonvalider.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonvalider.setText("Valider");
        buttonvalider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonvaliderActionPerformed(evt);
            }
        });
        jPanel1.add(buttonvalider);
        buttonvalider.setBounds(495, 240, 100, 31);
        jPanel1.add(caseid);
        caseid.setBounds(270, 250, 200, 20);

        buttonquitter.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonquitter.setText("Retour");
        buttonquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonquitterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonquitter);
        buttonquitter.setBounds(300, 360, 100, 31);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setText("Recher");
        fond.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(fond);
        fond.setBounds(0, 0, 710, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonvaliderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonvaliderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonvaliderActionPerformed

    private void buttonquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonquitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonquitterActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonquitter;
    private javax.swing.JButton buttonvalider;
    private javax.swing.JTextField caseid;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel ptitre;
    // End of variables declaration//GEN-END:variables
}
