/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;

/**
 *
 * @author mathi
 */
public class AAjouterEval extends javax.swing.JFrame {

    /**
     * Creates new form AAjouterEval
     */
    public AAjouterEval() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoece = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        matiere = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        note = new javax.swing.JLabel();
        appreciation = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        buttonretour = new javax.swing.JButton();
        casenote = new javax.swing.JTextField();
        caseid = new javax.swing.JTextField();
        choixmatiere = new javax.swing.JComboBox<>();
        bulletin = new javax.swing.JLabel();
        gtitre = new javax.swing.JLabel();
        choixbulletin = new javax.swing.JComboBox<>();
        caseappreciation = new javax.swing.JTextField();
        buttonvalider = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel1.setLayout(null);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        jPanel1.add(logoece);
        logoece.setBounds(30, 20, 267, 67);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Compte Enseignant");
        jPanel1.add(ptitre);
        ptitre.setBounds(400, 60, 250, 40);

        titre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(204, 204, 255));
        titre.setText("Ajouter une évaluation :");
        jPanel1.add(titre);
        titre.setBounds(190, 100, 310, 40);

        matiere.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        matiere.setForeground(new java.awt.Color(255, 255, 255));
        matiere.setText("Selectionner la Matière :");
        jPanel1.add(matiere);
        matiere.setBounds(170, 180, 160, 20);

        id.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        id.setText("Rentrer l'identifiant de l'élève :");
        jPanel1.add(id);
        id.setBounds(130, 150, 200, 20);

        note.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        note.setForeground(new java.awt.Color(255, 255, 255));
        note.setText("Entrer la note :");
        jPanel1.add(note);
        note.setBounds(220, 270, 100, 23);

        appreciation.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        appreciation.setForeground(new java.awt.Color(255, 255, 255));
        appreciation.setText("Entrer une Appréciation :");
        jPanel1.add(appreciation);
        appreciation.setBounds(160, 300, 160, 23);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(110, 250, 480, 20);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(110, 380, 480, 20);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(280, 420, 100, 31);
        jPanel1.add(casenote);
        casenote.setBounds(350, 270, 150, 20);
        jPanel1.add(caseid);
        caseid.setBounds(350, 150, 150, 20);

        choixmatiere.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixmatiere.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(choixmatiere);
        choixmatiere.setBounds(350, 180, 150, 20);

        bulletin.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setText("Selectionner le Bulletin :");
        jPanel1.add(bulletin);
        bulletin.setBounds(170, 210, 150, 23);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Mise à Jour Evaluation");
        jPanel1.add(gtitre);
        gtitre.setBounds(380, 20, 290, 50);

        choixbulletin.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixbulletin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(choixbulletin);
        choixbulletin.setBounds(350, 210, 150, 20);
        jPanel1.add(caseappreciation);
        caseappreciation.setBounds(350, 300, 150, 20);

        buttonvalider.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonvalider.setText("Valider");
        jPanel1.add(buttonvalider);
        buttonvalider.setBounds(290, 340, 80, 31);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        jPanel1.add(fond);
        fond.setBounds(0, -6, 700, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AAjouterEval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AAjouterEval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AAjouterEval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AAjouterEval.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AAjouterEval().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appreciation;
    private javax.swing.JLabel bulletin;
    private javax.swing.JButton buttonretour;
    private javax.swing.JButton buttonvalider;
    private javax.swing.JTextField caseappreciation;
    private javax.swing.JTextField caseid;
    private javax.swing.JTextField casenote;
    private javax.swing.JComboBox<String> choixbulletin;
    private javax.swing.JComboBox<String> choixmatiere;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JLabel id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel matiere;
    private javax.swing.JLabel note;
    private javax.swing.JLabel ptitre;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
