/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;

/**
 *
 * @author mathi
 */
public class tableProf extends javax.swing.JFrame {

    /**
     * Creates new form tableProf
     */
    public tableProf() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        casenom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        gtitre = new javax.swing.JLabel();
        Logoece = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        caseprenom = new javax.swing.JLabel();
        buttonretour = new javax.swing.JButton();
        tabelau = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        casenom.setBackground(new java.awt.Color(255, 255, 255));
        casenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        casenom.setForeground(new java.awt.Color(255, 255, 255));
        casenom.setText(" le nom doit s'afficher ici");
        jPanel1.add(casenom);
        casenom.setBounds(120, 130, 170, 23);

        prenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.setText("Prénom : ");
        jPanel1.add(prenom);
        prenom.setBounds(50, 160, 70, 23);

        nom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        nom.setText("Nom :");
        jPanel1.add(nom);
        nom.setBounds(70, 130, 40, 23);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Recherche et Informations :");
        jPanel1.add(gtitre);
        gtitre.setBounds(310, 40, 340, 30);

        Logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        Logoece.setText("jLabel1");
        jPanel1.add(Logoece);
        Logoece.setBounds(20, 20, 270, 60);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Proffesseur");
        jPanel1.add(ptitre);
        ptitre.setBounds(390, 80, 140, 50);

        caseprenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        caseprenom.setForeground(new java.awt.Color(255, 255, 255));
        caseprenom.setText("le prénom doit s'afficher ici");
        jPanel1.add(caseprenom);
        caseprenom.setBounds(120, 160, 220, 20);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(320, 380, 90, 40);

        jTable1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Année", "Classes", "Niveau", "Matières"
            }
        ));
        tabelau.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Année");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Classes");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Niveau");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Matières");
        }

        jPanel1.add(tabelau);
        tabelau.setBounds(150, 220, 400, 90);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setText("jLabel4");
        jPanel1.add(fond);
        fond.setBounds(0, 0, 710, 500);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logoece;
    private javax.swing.JButton buttonretour;
    private javax.swing.JLabel casenom;
    private javax.swing.JLabel caseprenom;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nom;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel ptitre;
    private javax.swing.JScrollPane tabelau;
    // End of variables declaration//GEN-END:variables
}
