/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class G_maj_prof_bulletin_ajouter extends javax.swing.JFrame {

    /**
     * Creates new form BBAjouter
     */
    public G_maj_prof_bulletin_ajouter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoece = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        case_idenseignement = new javax.swing.JTextField();
        idbulletin = new javax.swing.JLabel();
        idenseignement = new javax.swing.JLabel();
        case_appreciation = new javax.swing.JTextField();
        buttoninfo = new javax.swing.JButton();
        appreciation = new javax.swing.JLabel();
        case_idbulletin = new javax.swing.JTextField();
        note = new javax.swing.JLabel();
        case_note = new javax.swing.JTextField();
        buttonvalider = new javax.swing.JButton();
        buttonretour = new javax.swing.JButton();
        gtitre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));

        jPanel1.setLayout(null);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        jPanel1.add(logoece);
        logoece.setBounds(10, 10, 267, 67);

        ptitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Ajouter d' un champs du Bulltetin");
        jPanel1.add(ptitre);
        ptitre.setBounds(150, 110, 419, 44);

        case_idenseignement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                case_idenseignementActionPerformed(evt);
            }
        });
        jPanel1.add(case_idenseignement);
        case_idenseignement.setBounds(260, 220, 130, 20);

        idbulletin.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        idbulletin.setForeground(new java.awt.Color(255, 255, 255));
        idbulletin.setText("ID Bulletin :");
        jPanel1.add(idbulletin);
        idbulletin.setBounds(170, 190, 90, 23);

        idenseignement.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        idenseignement.setForeground(new java.awt.Color(255, 255, 255));
        idenseignement.setText("ID Enseignement :");
        jPanel1.add(idenseignement);
        idenseignement.setBounds(130, 220, 120, 20);
        jPanel1.add(case_appreciation);
        case_appreciation.setBounds(260, 300, 130, 20);

        buttoninfo.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttoninfo.setText("Informations");
        jPanel1.add(buttoninfo);
        buttoninfo.setBounds(430, 200, 120, 30);

        appreciation.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        appreciation.setForeground(new java.awt.Color(255, 255, 255));
        appreciation.setText("Appréciation :");
        jPanel1.add(appreciation);
        appreciation.setBounds(160, 300, 100, 20);
        jPanel1.add(case_idbulletin);
        case_idbulletin.setBounds(260, 190, 130, 20);

        note.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        note.setForeground(new java.awt.Color(255, 255, 255));
        note.setText("Note : ");
        jPanel1.add(note);
        note.setBounds(200, 270, 50, 23);
        jPanel1.add(case_note);
        case_note.setBounds(260, 270, 130, 20);

        buttonvalider.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonvalider.setText("Valider");
        jPanel1.add(buttonvalider);
        buttonvalider.setBounds(430, 280, 130, 31);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(270, 380, 110, 31);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Mise à jour");
        jPanel1.add(gtitre);
        gtitre.setBounds(510, 20, 150, 50);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(120, 250, 450, 10);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/JFrame/imagefond.jpg"))); // NOI18N
        fond.setText("jLabel9");
        jPanel1.add(fond);
        fond.setBounds(0, 0, 710, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void case_idenseignementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_case_idenseignementActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_case_idenseignementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_ajouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G_maj_prof_bulletin_ajouter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appreciation;
    private javax.swing.JButton buttoninfo;
    private javax.swing.JButton buttonretour;
    private javax.swing.JButton buttonvalider;
    private javax.swing.JTextField case_appreciation;
    private javax.swing.JTextField case_idbulletin;
    private javax.swing.JTextField case_idenseignement;
    private javax.swing.JTextField case_note;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JLabel idbulletin;
    private javax.swing.JLabel idenseignement;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel note;
    private javax.swing.JLabel ptitre;
    // End of variables declaration//GEN-END:variables
}
