/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class Menu_nouveau extends javax.swing.JFrame {

    /**
     * Creates new form Menu_nouveau
     */
    public Menu_nouveau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logoece = new javax.swing.JLabel();
        gtitre = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        buttonrecherche = new javax.swing.JButton();
        buttonmaj = new javax.swing.JButton();
        buttonreporting = new javax.swing.JButton();
        buttonquitter = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        Logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/JFrame/logoECE.jpg"))); // NOI18N
        jPanel1.add(Logoece);
        Logoece.setBounds(20, 20, 270, 60);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Bienvenue sur le site de gestion de l'ECE !");
        jPanel1.add(gtitre);
        gtitre.setBounds(100, 100, 530, 40);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Menu");
        jPanel1.add(ptitre);
        ptitre.setBounds(320, 150, 80, 50);

        buttonrecherche.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        buttonrecherche.setText("Recherche");
        jPanel1.add(buttonrecherche);
        buttonrecherche.setBounds(290, 210, 130, 50);

        buttonmaj.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        buttonmaj.setText("Mise à jour");
        jPanel1.add(buttonmaj);
        buttonmaj.setBounds(290, 270, 130, 50);

        buttonreporting.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        buttonreporting.setText("Reporting");
        jPanel1.add(buttonreporting);
        buttonreporting.setBounds(290, 330, 130, 50);

        buttonquitter.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        buttonquitter.setText("Quitter");
        buttonquitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonquitterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonquitter);
        buttonquitter.setBounds(290, 390, 130, 50);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/JFrame/imagefond.jpg"))); // NOI18N
        jPanel1.add(fond);
        fond.setBounds(0, -6, 700, 510);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 700, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonquitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonquitterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonquitterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_nouveau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_nouveau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logoece;
    private javax.swing.JButton buttonmaj;
    private javax.swing.JButton buttonquitter;
    private javax.swing.JButton buttonrecherche;
    private javax.swing.JButton buttonreporting;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ptitre;
    // End of variables declaration//GEN-END:variables
}
