/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class G_maj_prof_bulletin_supprimer extends javax.swing.JFrame {

    /**
     * Creates new form BBSupprimer
     */
    public G_maj_prof_bulletin_supprimer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ptitre = new javax.swing.JLabel();
        ID_champ_bulletin = new javax.swing.JLabel();
        case_idchamp_bulletin = new javax.swing.JTextField();
        buttoninfo = new javax.swing.JButton();
        buttonsupprimer = new javax.swing.JButton();
        buttonretour = new javax.swing.JButton();
        logoece = new javax.swing.JLabel();
        gtitre = new javax.swing.JLabel();
        titre = new javax.swing.JLabel();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Supprimer un champs du Bulletin");
        jPanel1.add(ptitre);
        ptitre.setBounds(160, 160, 430, 50);

        ID_champ_bulletin.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        ID_champ_bulletin.setForeground(new java.awt.Color(255, 255, 255));
        ID_champ_bulletin.setText("ID Champs Bulletin :");
        jPanel1.add(ID_champ_bulletin);
        ID_champ_bulletin.setBounds(120, 260, 130, 20);
        jPanel1.add(case_idchamp_bulletin);
        case_idchamp_bulletin.setBounds(280, 260, 140, 20);

        buttoninfo.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttoninfo.setText("Informations");
        buttoninfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttoninfoActionPerformed(evt);
            }
        });
        jPanel1.add(buttoninfo);
        buttoninfo.setBounds(480, 250, 130, 40);

        buttonsupprimer.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonsupprimer.setText("Supprimer");
        jPanel1.add(buttonsupprimer);
        buttonsupprimer.setBounds(290, 330, 120, 30);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        buttonretour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonretourActionPerformed(evt);
            }
        });
        jPanel1.add(buttonretour);
        buttonretour.setBounds(310, 450, 80, 30);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/JFrame/logoECE.jpg"))); // NOI18N
        jPanel1.add(logoece);
        logoece.setBounds(40, 30, 270, 60);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Mise à jour");
        jPanel1.add(gtitre);
        gtitre.setBounds(520, 20, 160, 60);

        titre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        titre.setForeground(new java.awt.Color(204, 204, 255));
        titre.setText("Enseignant");
        jPanel1.add(titre);
        titre.setBounds(520, 70, 150, 40);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/JFrame/imagefond.jpg"))); // NOI18N
        jPanel1.add(fond);
        fond.setBounds(0, 0, 760, 560);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 753, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttoninfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttoninfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttoninfoActionPerformed

    private void buttonretourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonretourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonretourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G_maj_prof_bulletin_supprimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G_maj_prof_bulletin_supprimer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_champ_bulletin;
    private javax.swing.JButton buttoninfo;
    private javax.swing.JButton buttonretour;
    private javax.swing.JButton buttonsupprimer;
    private javax.swing.JTextField case_idchamp_bulletin;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel ptitre;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
