/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class G_rechercher_prof extends javax.swing.JFrame {

    /**
     * Creates new form tableProf
     */
    public G_rechercher_prof() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gtitre = new javax.swing.JLabel();
        Logoece = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        buttonretour = new javax.swing.JButton();
        tabpane = new javax.swing.JScrollPane();
        tableau = new javax.swing.JTable();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 700));
        setPreferredSize(new java.awt.Dimension(1020, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setMinimumSize(new java.awt.Dimension(1020, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 700));
        jPanel1.setLayout(null);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Recherche et Informations :");
        jPanel1.add(gtitre);
        gtitre.setBounds(630, 40, 340, 30);

        Logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        Logoece.setText("jLabel1");
        jPanel1.add(Logoece);
        Logoece.setBounds(60, 40, 270, 60);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("Enseignants");
        jPanel1.add(ptitre);
        ptitre.setBounds(720, 80, 160, 50);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(430, 550, 90, 40);

        tableau.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        tableau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Enseignant", "Nom", "Prénom", "ID Enseignement", "ID Discipline", "Nom Discipline", "ID CLasse", "Nom Classe", "ID Niveau", "Niveau"
            }
        ));
        tabpane.setViewportView(tableau);

        jPanel1.add(tabpane);
        tabpane.setBounds(40, 190, 940, 320);

        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setText("jLabel4");
        fond.setMaximumSize(new java.awt.Dimension(1020, 700));
        fond.setMinimumSize(new java.awt.Dimension(1020, 700));
        fond.setPreferredSize(new java.awt.Dimension(1020, 700));
        jPanel1.add(fond);
        fond.setBounds(0, 0, 1060, 670);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logoece;
    private javax.swing.JButton buttonretour;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ptitre;
    private javax.swing.JTable tableau;
    private javax.swing.JScrollPane tabpane;
    // End of variables declaration//GEN-END:variables
}
