/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique.JFrame;

/**
 *
 * @author mathi
 */
public class G_recherche_eleve_info extends javax.swing.JFrame {

    /**
     * Creates new form tableeleve
     */
    public G_recherche_eleve_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gtitre = new javax.swing.JLabel();
        ptitre = new javax.swing.JLabel();
        logoece = new javax.swing.JLabel();
        Nom = new javax.swing.JLabel();
        casenom = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        caseprenom = new javax.swing.JLabel();
        annee = new javax.swing.JLabel();
        caseanne = new javax.swing.JLabel();
        classe = new javax.swing.JLabel();
        caseclase = new javax.swing.JLabel();
        bulletin = new javax.swing.JLabel();
        choixtrimestre = new javax.swing.JComboBox<>();
        choixannee = new javax.swing.JComboBox<>();
        buttonconsulter = new javax.swing.JButton();
        buttonretour = new javax.swing.JButton();
        fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        setResizable(false);

        jPanel1.setLayout(null);

        gtitre.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        gtitre.setForeground(new java.awt.Color(204, 204, 255));
        gtitre.setText("Recherche et Informations :");
        jPanel1.add(gtitre);
        gtitre.setBounds(320, 30, 350, 30);

        ptitre.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        ptitre.setForeground(new java.awt.Color(204, 204, 255));
        ptitre.setText("ELèves");
        jPanel1.add(ptitre);
        ptitre.setBounds(450, 60, 100, 40);

        logoece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/logoECE.jpg"))); // NOI18N
        jPanel1.add(logoece);
        logoece.setBounds(20, 20, 267, 67);

        Nom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        Nom.setForeground(new java.awt.Color(255, 255, 255));
        Nom.setText("Nom : ");
        jPanel1.add(Nom);
        Nom.setBounds(260, 130, 50, 20);

        casenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        casenom.setForeground(new java.awt.Color(255, 255, 255));
        casenom.setText("ici le Nom");
        jPanel1.add(casenom);
        casenom.setBounds(330, 130, 70, 20);

        prenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        prenom.setForeground(new java.awt.Color(255, 255, 255));
        prenom.setText("Prénom : ");
        jPanel1.add(prenom);
        prenom.setBounds(250, 160, 70, 30);

        caseprenom.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        caseprenom.setForeground(new java.awt.Color(255, 255, 255));
        caseprenom.setText("ici le prénom");
        jPanel1.add(caseprenom);
        caseprenom.setBounds(330, 160, 90, 30);

        annee.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        annee.setForeground(new java.awt.Color(255, 255, 255));
        annee.setText("Année actuelle :");
        jPanel1.add(annee);
        annee.setBounds(210, 200, 110, 20);

        caseanne.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        caseanne.setForeground(new java.awt.Color(255, 255, 255));
        caseanne.setText("ici l'année actuelle");
        jPanel1.add(caseanne);
        caseanne.setBounds(330, 200, 110, 23);

        classe.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        classe.setForeground(new java.awt.Color(255, 255, 255));
        classe.setText("Classe actuelle : ");
        jPanel1.add(classe);
        classe.setBounds(210, 240, 110, 23);

        caseclase.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        caseclase.setForeground(new java.awt.Color(255, 255, 255));
        caseclase.setText("ici l'année actuelle");
        jPanel1.add(caseclase);
        caseclase.setBounds(330, 240, 130, 20);

        bulletin.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        bulletin.setForeground(new java.awt.Color(255, 255, 255));
        bulletin.setText("Bulletin :");
        jPanel1.add(bulletin);
        bulletin.setBounds(220, 280, 60, 20);

        choixtrimestre.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixtrimestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(choixtrimestre);
        choixtrimestre.setBounds(330, 280, 140, 29);

        choixannee.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        choixannee.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        choixannee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                choixanneeItemStateChanged(evt);
            }
        });
        jPanel1.add(choixannee);
        choixannee.setBounds(330, 330, 140, 30);

        buttonconsulter.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonconsulter.setText("Consulter");
        jPanel1.add(buttonconsulter);
        buttonconsulter.setBounds(180, 330, 120, 30);

        buttonretour.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        buttonretour.setText("Retour");
        jPanel1.add(buttonretour);
        buttonretour.setBounds(290, 410, 90, 31);

        fond.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        fond.setForeground(new java.awt.Color(255, 255, 255));
        fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Graphique/imagefond.jpg"))); // NOI18N
        fond.setText("jLabel12");
        jPanel1.add(fond);
        fond.setBounds(0, 0, 700, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void choixanneeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_choixanneeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_choixanneeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(G_recherche_eleve_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(G_recherche_eleve_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(G_recherche_eleve_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(G_recherche_eleve_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new G_recherche_eleve_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Nom;
    private javax.swing.JLabel annee;
    private javax.swing.JLabel bulletin;
    private javax.swing.JButton buttonconsulter;
    private javax.swing.JButton buttonretour;
    private javax.swing.JLabel caseanne;
    private javax.swing.JLabel caseclase;
    private javax.swing.JLabel casenom;
    private javax.swing.JLabel caseprenom;
    private javax.swing.JComboBox<String> choixannee;
    private javax.swing.JComboBox<String> choixtrimestre;
    private javax.swing.JLabel classe;
    private javax.swing.JLabel fond;
    private javax.swing.JLabel gtitre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoece;
    private javax.swing.JLabel prenom;
    private javax.swing.JLabel ptitre;
    // End of variables declaration//GEN-END:variables
}
